on:
  workflow_call:
    secrets:
      SANITY_AUTH_TOKEN:
        required: true
    inputs:
      directory:
        required: true
        type: string
      name:
        required: true
        type: string

jobs:
  deploy_app:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3.0.2
        id: changes
        with:
          filters: |
            app:
              - '${{ inputs.directory }}/**'
      - run: corepack enable
      - uses: actions/setup-node@v4
        if: ${{ steps.changes.outputs.app == 'true' }}
        with:
          node-version: 22
          cache: yarn
      - run: yarn install --immutable
        if: ${{ steps.changes.outputs.app == 'true' }}
      - name: ${{ inputs.name }}
        if: ${{ steps.changes.outputs.app == 'true' }}
        working-directory: ${{ inputs.directory }}
        run: yarn deploy
