on:
  workflow_call:
    inputs:
      directory:
        required: true
        type: string
      name:
        required: true
        type: string
jobs:
  deploy_app:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn
      - run: yarn install --immutable
      - name: Deploy ${{inputs.name}} app
        working-directory: ${{inputs.directory}}
        run: yarn deploy
