name: Deploy Sanity Studio

permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - master

env:
  SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
  STUDIO_HOSTNAME: ${{ vars.STUDIO_HOSTNAME }}
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}-deploy

jobs:
  deploy:
    name: Deploy production
    runs-on: ubuntu-22.04

    environment:
      name: Production

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn
      - run: yarn install --frozen-lockfile

      - name: Set Studio hostname
        run: echo "SANITY_STUDIO_HOSTNAME=${STUDIO_HOSTNAME}" >> $GITHUB_ENV

      - name: Build and deploy Sanity Studio
        id: deploy
        run: |
          yarn deploy --yes
          echo "STUDIO_URL=https://${SANITY_STUDIO_HOSTNAME}.sanity.studio" >> $GITHUB_OUTPUT
